-- MySQL Script generated by MySQL Workbench
-- Mon Jul 31 21:00:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `littlelemondb` ;

-- -----------------------------------------------------
-- Schema littlelemondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `littlelemondb` DEFAULT CHARACTER SET utf8 ;
USE `littlelemondb` ;

-- -----------------------------------------------------
-- Table `littlelemondb`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Employees` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Employees` (
  `EmployeeID` INT NOT NULL,
  `EmployeeFirstName` VARCHAR(45) NOT NULL,
  `EmployeeLastName` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Salary` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Customers` (
  `CustomerID` INT NOT NULL,
  `CustomerFirstName` VARCHAR(45) NOT NULL,
  `CustomerLastName` VARCHAR(45) NOT NULL,
  `CustomerPhoneNumber` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Bookings` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Bookings` (
  `BookingID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `TableNo` INT NOT NULL,
  `BookingSlot` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `employeeid_idx` (`EmployeeID` ASC) VISIBLE,
  INDEX `customerid_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `employeeid`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `littlelemondb`.`Employees` (`EmployeeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `customerid`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `littlelemondb`.`Customers` (`CustomerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Items` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Items` (
  `ItemID` INT NOT NULL,
  `ItemDesc` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Menu` (
  `MenuID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  `Cuisine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `itemid_idx` (`ItemID` ASC) VISIBLE,
  CONSTRAINT `itemid`
    FOREIGN KEY (`ItemID`)
    REFERENCES `littlelemondb`.`Items` (`ItemID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`OrderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`OrderStatus` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`OrderStatus` (
  `StatusID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `DeliveryDate` DATE NULL,
  PRIMARY KEY (`StatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`Orders` (
  `OrderID` INT NOT NULL,
  `MenuID` INT NOT NULL,
  `BookingID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `TotalBill` DECIMAL(10,2) NOT NULL,
  `StatusID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `menuid_idx` (`MenuID` ASC) VISIBLE,
  INDEX `bookingid_idx` (`BookingID` ASC) VISIBLE,
  INDEX `statusid_idx` (`StatusID` ASC) VISIBLE,
  CONSTRAINT `menuid`
    FOREIGN KEY (`MenuID`)
    REFERENCES `littlelemondb`.`Menu` (`MenuID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookingid`
    FOREIGN KEY (`BookingID`)
    REFERENCES `littlelemondb`.`Bookings` (`BookingID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `statusid`
    FOREIGN KEY (`StatusID`)
    REFERENCES `littlelemondb`.`OrderStatus` (`StatusID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`menuitems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`menuitems` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`menuitems` (
  `itemid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`itemid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`menus` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`menus` (
  `menuid` INT NOT NULL,
  `itemid` INT NOT NULL,
  `cuisine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menuid`),
  INDEX `itemid_fk_idx` (`itemid` ASC) VISIBLE,
  CONSTRAINT `itemid_fk`
    FOREIGN KEY (`itemid`)
    REFERENCES `littlelemondb`.`menuitems` (`itemid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`employees` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`employees` (
  `employeeid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `contact_number` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `annual_salary` INT NOT NULL,
  PRIMARY KEY (`employeeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`customers` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`customers` (
  `customerid` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phonenumber` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`customerid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`bookings` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`bookings` (
  `bookingid` INT NOT NULL,
  `tableno` INT NOT NULL,
  `GuestFirstName` VARCHAR(45) NOT NULL,
  `GuestLastName` VARCHAR(45) NOT NULL,
  `BookingSlot` VARCHAR(45) NOT NULL,
  `EmployeeID` INT NOT NULL,
  `customerid` INT NOT NULL,
  PRIMARY KEY (`bookingid`),
  INDEX `employeeid_idx` (`EmployeeID` ASC) VISIBLE,
  INDEX `customerid_idx` (`customerid` ASC) VISIBLE,
  CONSTRAINT `employeeid_fk`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `littlelemondb`.`employees` (`employeeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `customerid_fk`
    FOREIGN KEY (`customerid`)
    REFERENCES `littlelemondb`.`customers` (`customerid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`orders` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`orders` (
  `orderid` INT NOT NULL,
  `tableno` INT NOT NULL,
  `menuid` INT NOT NULL,
  `bookingid` INT NOT NULL,
  `quantity` INT NOT NULL,
  `billamount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `menuid_idx` (`menuid` ASC) VISIBLE,
  INDEX `bookingid_idx` (`bookingid` ASC) VISIBLE,
  CONSTRAINT `menuid_fk`
    FOREIGN KEY (`menuid`)
    REFERENCES `littlelemondb`.`menus` (`menuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `bookingid_fk`
    FOREIGN KEY (`bookingid`)
    REFERENCES `littlelemondb`.`bookings` (`bookingid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `littlelemondb`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `littlelemondb`.`delivery` ;

CREATE TABLE IF NOT EXISTS `littlelemondb`.`delivery` (
  `deliveryid` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `status_dt` DATETIME NOT NULL,
  `orderid` INT NOT NULL,
  PRIMARY KEY (`deliveryid`),
  INDEX `orderid_fk_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `orderid_fk`
    FOREIGN KEY (`orderid`)
    REFERENCES `littlelemondb`.`orders` (`orderid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
